### ISSUE TITLE
Error "already piped"

### ISSUE THREAD

**Issue by richardschneider** [libp2p/js-libp2p-switch#235]
`js-ipfs 0.4.7` was running on a windows machine for a few hours and then raised the following error.

```
C:\Users\Owner\Documents\GitHub\js-ipfs>node src\cli\bin.js daemon
Initializing daemon...
Swarm listening on /p2p-circuit/ipfs/QmYHExHtTzFEjdwyQcJkD9gaKKgfwvGswoFb4simrJn5Q6
Swarm listening on /p2p-circuit/ip4/0.0.0.0/tcp/4002/ipfs/QmYHExHtTzFEjdwyQcJkD9gaKKgfwvGswoFb4simrJn5Q6
Swarm listening on /p2p-circuit/ip4/127.0.0.1/tcp/4003/ws/ipfs/QmYHExHtTzFEjdwyQcJkD9gaKKgfwvGswoFb4simrJn5Q6
Swarm listening on /ip4/127.0.0.1/tcp/4003/ws/ipfs/QmYHExHtTzFEjdwyQcJkD9gaKKgfwvGswoFb4simrJn5Q6
Swarm listening on /ip4/192.168.178.21/tcp/4002/ipfs/QmYHExHtTzFEjdwyQcJkD9gaKKgfwvGswoFb4simrJn5Q6
Swarm listening on /ip4/127.0.0.1/tcp/4002/ipfs/QmYHExHtTzFEjdwyQcJkD9gaKKgfwvGswoFb4simrJn5Q6
API is listening on: /ip4/127.0.0.1/tcp/5002
Gateway (readonly) is listening on: /ip4/127.0.0.1/tcp/9090
Daemon is ready
C:\Users\Owner\Documents\GitHub\js-ipfs\node_modules\pull-pair\index.js:11
      throw new Error('already piped')
      ^

Error: already piped
    at sink (C:\Users\Owner\Documents\GitHub\js-ipfs\node_modules\pull-pair\index.js:11:13)
    at consume (C:\Users\Owner\Documents\GitHub\js-ipfs\node_modules\pull-defer\sink.js:7:17)
    at Connection.consume (C:\Users\Owner\Documents\GitHub\js-ipfs\node_modules\pull-defer\sink.js:7:17)
    at pull (C:\Users\Owner\Documents\GitHub\js-ipfs\node_modules\pull-stream\pull.js:43:9)
    at Dialer.handle (C:\Users\Owner\Documents\GitHub\js-ipfs\node_modules\multistream-select\src\dialer\index.js:47:5)
    at attemptMuxerUpgrade (C:\Users\Owner\Documents\GitHub\js-ipfs\node_modules\libp2p-swarm\src\dial.js:159:10)
    at gotWarmedUpConn (C:\Users\Owner\Documents\GitHub\js-ipfs\node_modules\libp2p-swarm\src\dial.js:53:7)
    at Swarm.dial (C:\Users\Owner\Documents\GitHub\js-ipfs\node_modules\libp2p-swarm\src\dial.js:40:9)
    at _getPeerInfo (C:\Users\Owner\Documents\GitHub\js-ipfs\node_modules\libp2p\src\index.js:265:18)
    at setImmediate (C:\Users\Owner\Documents\GitHub\js-ipfs\node_modules\libp2p\src\index.js:324:24)
```

**Comment by dryajov** [comment]
@richardschneider is that version really js-ipfs? 

I get:

```
$ jsipfs version
js-ipfs version: 0.26.0
```

If it is, then it's a really old version. 

I think you might be running master, since I see the /p2p-circuit addresses stuff being printed and that hasn't been released, AFAIK? Either way, something is up and just want to make sure we got the correct version.

**Comment by richardschneider** [comment]
@dryajov You are right, I  don't know where I got that version number.  You are correct, I am running from `master`.

**Comment by ztl8702** [comment]
Got hit by a possibly related issue: https://github.com/ipfs/js-ipfs/issues/1156

I don't know how to reproduce it tho.

**Comment by mitra42** [comment]
Sorry the ipfs/js-ipfs#1156 issue got confused as it was reported as a potential symptom of a different problem. The "already-piped" issue is still happening, certainly on v0.28.1 and probably on v0.28.2

**Comment by jacobheun** [comment]
I can confirm this is still occurring on v0.28.2.
Here is an updated stack trace on OSX for v0.28.2
```
/Users/…/js-libp2p-secio/node_modules/pull-pair/index.js:11
      throw new Error('already piped')
      ^

Error: already piped
    at sink (/Users/…/js-libp2p-secio/node_modules/pull-pair/index.js:11:13)
    at consume (/Users/…/js-libp2p-secio/node_modules/pull-defer/sink.js:7:17)
    at consume (/Users/…/js-libp2p-secio/node_modules/pull-defer/sink.js:7:17)
    at Connection.consume (/Users/…/js-libp2p-secio/node_modules/pull-defer/sink.js:7:17)
    at pull (/Users/…/js-ipfs-docker/node_modules/pull-stream/pull.js:43:9)
    at Dialer.handle (/Users/…/js-ipfs-docker/node_modules/multistream-select/src/dialer/index.js:47:5)
    at attemptMuxerUpgrade (/Users/…/js-ipfs-docker/node_modules/libp2p-switch/src/dial.js:157:10)
    at gotWarmedUpConn (/Users/…/js-ipfs-docker/node_modules/libp2p-switch/src/dial.js:54:7)
    at Switch.dial (/Users/…/js-ipfs-docker/node_modules/libp2p-switch/src/dial.js:40:9)
    at _getPeerInfo (/Users/…/js-ipfs-docker/node_modules/libp2p/src/index.js:237:19)
```

**Comment by harrshasri** [comment]
Mee too
Same Error Here
`Uncaught Error: already piped
    at sink '

**Comment by shessenauer** [comment]
bump, this is killing my application

**Comment by jacobheun** [comment]
@shessenauer can you provide a stack trace and the version of ipfs you are using?

**Comment by shessenauer** [comment]
@jacobheun Thanks for getting back to me so quickly. 
Currently using:   IPFS-JS  "version": "0.28.2"

Inside of a Node.JS application running in a Linux EC2 docker container 

`/Users/myName/Documents/Software/git.nosync/myApp/node_modules/pull-pair/index.js:11
      throw new Error('already piped')
      ^

Error: already piped
    at sink (/Users/myName/Documents/Software/git.nosync/myApp/node_modules/pull-pair/index.js:11:13)
    at consume (/Users/myName/Documents/Software/git.nosync/myApp/node_modules/pull-defer/sink.js:7:17)
    at consume (/Users/myName/Documents/Software/git.nosync/myApp/node_modules/pull-defer/sink.js:7:17)
    at Connection.consume (/Users/myName/Documents/Software/git.nosync/myApp/node_modules/pull-defer/sink.js:7:17)
    at pull (/Users/myName/Documents/Software/git.nosync/myApp/node_modules/pull-stream/pull.js:43:9)
    at Dialer.handle (/Users/myName/Documents/Software/git.nosync/myApp/node_modules/multistream-select/src/dialer/index.js:47:5)
    at attemptMuxerUpgrade (/Users/myName/Documents/Software/git.nosync/myApp/node_modules/libp2p-switch/src/dial.js:157:10)
    at gotWarmedUpConn (/Users/myName/Documents/Software/git.nosync/myApp/node_modules/libp2p-switch/src/dial.js:54:7)
    at Switch.dial (/Users/myName/Documents/Software/git.nosync/myApp/node_modules/libp2p-switch/src/dial.js:40:9)
    at _getPeerInfo (/Users/myName/Documents/Software/git.nosync/myApp/node_modules/libp2p/src/index.js:237:19)
[nodemon] app crashed - waiting for file changes before starting...`

**Comment by jacobheun** [comment]
@shessenauer okay, this should be released with js-ipfs 0.30.0. It should be resolved in libp2p-switch 0.40.2 (current version is 0.40.4), but is pending an update to libp2p in js-ipfs.

If you need the fix sooner, I'd recommend leveraging yarn for installation and adding `"libp2p-switch": "~0.40.4"` to the `resolutions` block in package.json.

**Comment by shessenauer** [comment]
@jacobheun Made the yarn switch with your recommendation and works like a charm. Thank you so much

**Comment by jacobheun** [comment]
@shessenauer that's great, thanks for following up!
