### ISSUE TITLE
Uncaught Error: Multiplexer is destroyed

### ISSUE THREAD

**Issue by pgte** [libp2p/js-libp2p-switch#263]
Occasionally I get this uncaught error:

```
     Uncaught Error: Multiplexer is destroyed
      at Multiplex.createStream (/Users/pedroteixeira/projects/ipfs/js-ipfs/node_modules/libp2p-mplex/src/internals/index.js:95:13)
      at MultiplexMuxer.newStream (/Users/pedroteixeira/projects/ipfs/js-ipfs/node_modules/libp2p-mplex/src/muxer.js:54:33)
      at openConnInMuxedConn (/Users/pedroteixeira/projects/ipfs/js-ipfs/node_modules/libp2p-switch/src/dial.js:211:16)
      at gotMuxer (/Users/pedroteixeira/projects/ipfs/js-ipfs/node_modules/libp2p-switch/src/dial.js:80:7)
      at Switch.dial (/Users/pedroteixeira/projects/ipfs/js-ipfs/node_modules/libp2p-switch/src/dial.js:47:7)
      at _getPeerInfo (/Users/pedroteixeira/projects/ipfs/js-ipfs/node_modules/libp2p/src/index.js:258:19)
```

**Comment by jacobheun** [comment]
@pgte it looks like you resolved this with https://github.com/libp2p/js-libp2p-mplex/pull/79, which is available in 0.80 libp2p-mplex, woo! Going to close this issue.
