### ISSUE TITLE
Dial failing for dns4/dnsaddr multiaddrs

### ISSUE THREAD

**Issue by mgoelzer** [libp2p/js-libp2p-switch#277]
I have a peer that I can dial by IP, but not by DNS hostname.  I have tried both `/dns4/` and `/dnsaddr/` and get the same error in `libp2p-switch/src/dial.js`.

Does js-libp2p not support DNS multiaddrs?  Or is this a bug?

Here is output showing the program works correctly when given an `/ip4/` multiaddr:
```
$ node js-dht-test/index.js /ip4/159.89.221.55/tcp/9876/ipfs/QmZ5adxeh2GnafXdbHgUFveEKJX5pWihGhBEQMWbFNHE34
Connecting to: /ip4/159.89.221.55/tcp/9876/ipfs/QmZ5adxeh2GnafXdbHgUFveEKJX5pWihGhBEQMWbFNHE34
Local node QmXLxtry1x9k2wjXfWQnM2JqFc6hAw4SCTsyd68kRUtM4m is providing QmTp9VkYvnHyrqKQuFPiuZkiX9gPcqj6x5LJ1rmWuSySnL
Remote node QmZ5adxeh2GnafXdbHgUFveEKJX5pWihGhBEQMWbFNHE34 is providing zb2rhXqLbdjpXnJG99QsjM6Nc6xaDKgEr2FfugDJynE7H2NR6
```

But the same program fails with a `/dns4/` multiaddr:
```
$ node js-dht-test/index.js /dns4/libp2p-bootstrap.goelzer.io/tcp/9876/ipfs/QmcUMtJVQWzc1RGPG2VeC1fvtBw1DZu92er4URFM2m546x
Connecting to: /dns4/libp2p-bootstrap.goelzer.io/tcp/9876/ipfs/QmcUMtJVQWzc1RGPG2VeC1fvtBw1DZu92er4URFM2m546x
/home/mike/libp2p-demo-go-js-rust/js-dht-test/index.js:68
    if (err) { throw err }
               ^

Error: Circuit not enabled and all transports failed to dial peer QmcUMtJVQWzc1RGPG2VeC1fvtBw1DZu92er4URFM2m546x!
    at nextTransport (/home/mike/libp2p-demo-go-js-rust/js-dht-test/node_modules/libp2p-switch/src/dial.js:365:27)
    at Dialer._attemptDial (/home/mike/libp2p-demo-go-js-rust/js-dht-test/node_modules/libp2p-switch/src/dial.js:390:5)
    at waterfall (/home/mike/libp2p-demo-go-js-rust/js-dht-test/node_modules/libp2p-switch/src/dial.js:190:14)
    at nextTask (/home/mike/libp2p-demo-go-js-rust/js-dht-test/node_modules/async/waterfall.js:16:14)
    at exports.default (/home/mike/libp2p-demo-go-js-rust/js-dht-test/node_modules/async/waterfall.js:26:5)
    at Dialer._createBaseConnection (/home/mike/libp2p-demo-go-js-rust/js-dht-test/node_modules/libp2p-switch/src/dial.js:188:5)
    at waterfall (/home/mike/libp2p-demo-go-js-rust/js-dht-test/node_modules/libp2p-switch/src/dial.js:135:14)
    at nextTask (/home/mike/libp2p-demo-go-js-rust/js-dht-test/node_modules/async/waterfall.js:16:14)
    at exports.default (/home/mike/libp2p-demo-go-js-rust/js-dht-test/node_modules/async/waterfall.js:26:5)
    at Dialer._establishConnection (/home/mike/libp2p-demo-go-js-rust/js-dht-test/node_modules/libp2p-switch/src/dial.js:132:5)
```

And also fails with a `/dnsaddr/` multiaddr:
```
$ node js-dht-test/index.js /dnsaddr/libp2p-bootstrap.goelzer.io/tcp/9876/ipfs/QmcUMtJVQWzc1RGPG2VeC1fvtBw1DZu92er4URFM2m546x
Connecting to: /dnsaddr/libp2p-bootstrap.goelzer.io/tcp/9876/ipfs/QmcUMtJVQWzc1RGPG2VeC1fvtBw1DZu92er4URFM2m546x
/home/mike/libp2p-demo-go-js-rust/js-dht-test/index.js:68
    if (err) { throw err }
               ^

Error: Circuit not enabled and all transports failed to dial peer QmcUMtJVQWzc1RGPG2VeC1fvtBw1DZu92er4URFM2m546x!
    at nextTransport (/home/mike/libp2p-demo-go-js-rust/js-dht-test/node_modules/libp2p-switch/src/dial.js:365:27)
    at Dialer._attemptDial (/home/mike/libp2p-demo-go-js-rust/js-dht-test/node_modules/libp2p-switch/src/dial.js:390:5)
    at waterfall (/home/mike/libp2p-demo-go-js-rust/js-dht-test/node_modules/libp2p-switch/src/dial.js:190:14)
    at nextTask (/home/mike/libp2p-demo-go-js-rust/js-dht-test/node_modules/async/waterfall.js:16:14)
    at exports.default (/home/mike/libp2p-demo-go-js-rust/js-dht-test/node_modules/async/waterfall.js:26:5)
    at Dialer._createBaseConnection (/home/mike/libp2p-demo-go-js-rust/js-dht-test/node_modules/libp2p-switch/src/dial.js:188:5)
    at waterfall (/home/mike/libp2p-demo-go-js-rust/js-dht-test/node_modules/libp2p-switch/src/dial.js:135:14)
    at nextTask (/home/mike/libp2p-demo-go-js-rust/js-dht-test/node_modules/async/waterfall.js:16:14)
    at exports.default (/home/mike/libp2p-demo-go-js-rust/js-dht-test/node_modules/async/waterfall.js:26:5)
    at Dialer._establishConnection (/home/mike/libp2p-demo-go-js-rust/js-dht-test/node_modules/libp2p-switch/src/dial.js:132:5)
```

`libp2p-bootstrap.goelzer.io` and `159.89.221.55` are the same server.  Full source code of the test program is here:  [github.com/mgoelzer/libp2p-demo-go-js-rust/tree/jhiesey-dht-interop/js-dht-test](https://github.com/mgoelzer/libp2p-demo-go-js-rust/tree/jhiesey-dht-interop/js-dht-test)

/ cc @jacobheun @vasco-santos (would know if js-libp2p is even expected to support dns multiaddrs)
/ cc @jhiesey (for interest)

**Comment by jacobheun** [comment]
Yes, there is a known issue with the tcp transport not being able to dial dns addresses. https://github.com/libp2p/js-libp2p-tcp/issues/95

**Comment by mgoelzer** [comment]
@jacobheun Thanks for taking a look.

Closing this as a dup of https://github.com/libp2p/js-libp2p-tcp/issues/95.
