### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by alanshaw** [libp2p/js-libp2p-switch#287]
```js
/Users/alan/Code/protocol-labs/js-ipfs/node_modules/libp2p-switch/src/observer.js:41
    peerInfo.then((_peerInfo) => {
             ^

RangeError: Maximum call stack size exceeded
    at Promise.then (<anonymous>)
    at willObserve (/Users/alan/Code/protocol-labs/js-ipfs/node_modules/libp2p-switch/src/observer.js:41:14)
    at pull.map (/Users/alan/Code/protocol-labs/js-ipfs/node_modules/libp2p-switch/src/observer.js:34:9)
    at /Users/alan/Code/protocol-labs/js-ipfs/node_modules/pull-stream/throughs/map.js:13:23
    at /Users/alan/Code/protocol-labs/js-ipfs/node_modules/pull-reader/index.js:114:13
    at /Users/alan/Code/protocol-labs/js-ipfs/node_modules/pull-reader/index.js:114:13
    at onNext (/Users/alan/Code/protocol-labs/js-ipfs/node_modules/pull-catch/index.js:17:17)
    at drain (/Users/alan/Code/protocol-labs/js-ipfs/node_modules/stream-to-pull-stream/index.js:141:18)
    at Channel.<anonymous> (/Users/alan/Code/protocol-labs/js-ipfs/node_modules/stream-to-pull-stream/index.js:150:5)
    at Channel.emit (events.js:182:13)
```

**Comment by jacobheun** [comment]
@alanshaw any other info on the state of the node when this happened? Testing/idle node/etc.

**Comment by alanshaw** [comment]
Sorry, should lave left more context - just wanted to get this logged before I forgot!

It's a JS IPFS daemon running on this branch https://github.com/ipfs/js-ipfs/pull/856

I'm using companion and I opened the WebUI, looked around a bit and clicked on the peers page to see the hundreds of nodes (very exciting btw), shortly after my daemon crashed with that error.

**Comment by alanshaw** [comment]
Biggest stack I have ever seen https://ci.ipfs.team/blue/rest/organizations/jenkins/pipelines/IPFS/pipelines/js-ipfs/branches/PR-856/runs/80/nodes/257/steps/386/log/?start=0

**Comment by achingbrain** [comment]
Seeing this in Jenkins again today:

```
2018-12-19T11:47:31.635Z ipfsd-ctl:daemon:stderr /tmp/jenkins/workspace/PFS_interop_test-with-debug-NUL3VSMMUZYNRCKUQJKWVW6DEXXEDFCXGEMGCBOBYZCZKZUXXGHA@2/node_modules/libp2p-switch/src/observer.js:41
    peerInfo.then((_peerInfo) => {
             ^

RangeError: Maximum call stack size exceeded
    at Promise.then (<anonymous>)
    at willObserve (/tmp/jenkins/workspace/PFS_interop_test-with-debug-NUL3VSMMUZYNRCKUQJKWVW6DEXXEDFCXGEMGCBOBYZCZKZUXXGHA@2/node_modules/libp2p-switch/src/observer.js:41:14)
    at pull.map (/tmp/jenkins/workspace/PFS_interop_test-with-debug-NUL3VSMMUZYNRCKUQJKWVW6DEXXEDFCXGEMGCBOBYZCZKZUXXGHA@2/node_modules/libp2p-switch/src/observer.js:34:9)
    at /tmp/jenkins/workspace/PFS_interop_test-with-debug-NUL3VSMMUZYNRCKUQJKWVW6DEXXEDFCXGEMGCBOBYZCZKZUXXGHA@2/node_modules/pull-stream/throughs/map.js:13:23
    at /tmp/jenkins/workspace/PFS_interop_test-with-debug-NUL3VSMMUZYNRCKUQJKWVW6DEXXEDFCXGEMGCBOBYZCZKZUXXGHA@2/node_modules/pull-reader/index.js:114:13
    at /tmp/jenkins/workspace/PFS_interop_test-with-debug-NUL3VSMMUZYNRCKUQJKWVW6DEXXEDFCXGEMGCBOBYZCZKZUXXGHA@2/node_modules/pull-reader/index.js:114:13
    at /tmp/jenkins/workspace/PFS_interop_test-with-debug-NUL3VSMMUZYNRCKUQJKWVW6DEXXEDFCXGEMGCBOBYZCZKZUXXGHA@2/node_modules/pull-reader/index.js:114:13
    at /tmp/jenkins/workspace/PFS_interop_test-with-debug-NUL3VSMMUZYNRCKUQJKWVW6DEXXEDFCXGEMGCBOBYZCZKZUXXGHA@2/node_modules/pull-stream/throughs/async-map.js:39:20
    at decipher.decrypt (/tmp/jenkins/workspace/PFS_interop_test-with-debug-NUL3VSMMUZYNRCKUQJKWVW6DEXXEDFCXGEMGCBOBYZCZKZUXXGHA@2/node_modules/libp2p-secio/src/etm.js:64:11)
    at Object.decrypt (/tmp/jenkins/workspace/PFS_interop_test-with-debug-NUL3VSMMUZYNRCKUQJKWVW6DEXXEDFCXGEMGCBOBYZCZKZUXXGHA@2/node_modules/libp2p-crypto/src/aes/index.js:25:7)
```

**Comment by mcollina** [comment]
This is likely my fault. I removed a setImmediate where the event was emitted. That should either a) be reintroduced or b) added as a process.nextTick.

**Comment by mcollina** [comment]
This was the PR: https://github.com/libp2p/js-libp2p-switch/pull/289.

**Comment by achingbrain** [comment]
@mcollina this one? https://github.com/libp2p/js-libp2p-switch/pull/289/files#diff-08f3e9ab539253c87ea111cc61c69e29

**Comment by achingbrain** [comment]
Aha, yeah.

**Comment by mcollina** [comment]
yes.

**Comment by jacobheun** [comment]
We were seeing the call stack prior to that switch update being released. It might be contributing, but I don't think it's the core issue.

**Comment by mcollina** [comment]
I would recommend to add a `Error.stackTraceLimit = 1024` somewhere to get a bit more of 10 lines.

**Comment by jacobheun** [comment]
Okay, I've got a branch of the interop tests passing based off the latest ipfs rc candidate, https://ci.ipfs.team/blue/organizations/jenkins/IPFS%2Finterop/detail/test%2Ffix-async/4/pipeline/254.

The underlying issue seems to be due to a lot of asynchronous code calling their callbacks synchronously, which is bloating the stack. I'll have a few PRs out in a bit for the code I updated to help alleviate the issue.
